# Generated by Django 5.1.7 on 2025-08-22 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_region', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom_region'],
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('type_operateur', models.CharField(choices=[('CONFIRMATION', 'Opérateur de Confirmation'), ('LOGISTIQUE', 'Opérateur Logistique'), ('PREPARATION', 'Opérateur de Préparation'), ('ADMIN', 'Administrateur'), ('SUPERVISEUR_PREPARATION', 'Superviseur de Préparation')], default='CONFIRMATION', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/operateurs/')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_operateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'administrateur", null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire optionnel sur la modification', null=True)),
                ('administrateur', models.ForeignKey(blank=True, help_text='Administrateur qui a modifié le mot de passe', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_mots_de_passe', to='parametre.operateur')),
            ],
            options={
                'verbose_name': 'Historique Mot de Passe',
                'verbose_name_plural': 'Historiques Mots de Passe',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('frais_livraison', models.FloatField()),
                ('frequence_livraison', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='parametre.region')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
                'unique_together': {('nom', 'region')},
            },
        ),
    ]
