# Generated by Django 5.1.7 on 2025-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
