# Generated by Django 5.1.7 on 2025-06-16 12:47

from django.db import migrations
import datetime # Ajout de l'import pour datetime

def populate_ville_defaults(apps, schema_editor):
    Ville = apps.get_model('parametre', 'Ville')
    Region = apps.get_model('parametre', 'Region')

    # Créer ou récupérer la région par défaut si elle n'existe pas
    default_region, created = Region.objects.get_or_create(nom_region='Non spécifiée')

    for ville in Ville.objects.all():
        needs_save = False
        if ville.frais_livraison is None:
            ville.frais_livraison = 0.0
            needs_save = True
        if not ville.frequence_livraison: # Vérifie si la chaîne est vide ou None
            ville.frequence_livraison = 'Quotidienne'
            needs_save = True
        if ville.region is None:
            ville.region = default_region
            needs_save = True
        
        if needs_save:
            ville.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_ville_defaults, reverse_code=migrations.RunPython.noop),
    ]