# Generated by Django 5.1.7 on 2025-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_populate_ville_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='type_operateur',
            field=models.CharField(choices=[('CONFIRMATION', 'Opérateur de Confirmation'), ('LOGISTIQUE', 'Opérateur Logistique'), ('PREPARATION', 'Opérateur de Préparation'), ('ADMIN', 'Administrateur')], default='CONFIRMATION', max_length=20),
        ),
    ]
