# Generated by Django 5.1.7 on 2025-06-26 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0003_alter_operateur_type_operateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'administrateur", null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire optionnel sur la modification', null=True)),
                ('administrateur', models.ForeignKey(blank=True, help_text='Administrateur qui a modifié le mot de passe', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_mots_de_passe', to='parametre.operateur')),
            ],
            options={
                'verbose_name': 'Historique Mot de Passe',
                'verbose_name_plural': 'Historiques Mots de Passe',
                'ordering': ['-date_modification'],
            },
        ),
    ]
