# Generated by Django 5.1.7 on 2025-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0004_add_historique_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='type_operateur',
            field=models.CharField(choices=[('CONFIRMATION', 'Opérateur de Confirmation'), ('LOGISTIQUE', 'Opérateur Logistique'), ('PREPARATION', 'Opérateur de Préparation'), ('ADMIN', 'Administrateur'), ('LIVREUR', 'Livreur')], default='CONFIRMATION', max_length=20),
        ),
    ]
