# Generated by Django 5.1.7 on 2025-08-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0006_pagination_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginationpreset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userpaginationpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaginationConfig',
        ),
        migrations.DeleteModel(
            name='PaginationPreset',
        ),
        migrations.DeleteModel(
            name='UserPaginationPreference',
        ),
    ]
