# Generated by Django 5.1.7 on 2025-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0007_pagination_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='type_operateur',
            field=models.CharField(choices=[('CONFIRMATION', 'Opérateur de Confirmation'), ('LOGISTIQUE', 'Opérateur Logistique'), ('PREPARATION', 'Opérateur de Préparation'), ('ADMIN', 'Administrateur'), ('SUPERVISEUR_PREPARATION', 'Superviseur de Préparation')], default='CONFIRMATION', max_length=30),
        ),
    ]
