# Generated by Django 5.1.7 on 2025-06-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_remove_client_actif_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
