# Generated by Django 5.1.7 on 2025-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_tel',
            field=models.CharField(max_length=30, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
