# Generated by Django 5.1.7 on 2025-06-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatcommande',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etats_modifies', to='parametre.operateur'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('ANNULATION', 'Annulation'), ('PREPARATION', 'Préparation'), ('EXPEDITION', 'Expédition'), ('LIVRAISON', 'Livraison'), ('RETOUR', 'Retour'), ('MODIFICATION', 'Modification'), ('COMMENTAIRE', 'Commentaire')], max_length=20),
        ),
    ]
