# Generated by Django 5.1.7 on 2025-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_modele'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='panier',
            name='variante_id',
            field=models.IntegerField(blank=True, help_text='ID de la variante sélectionnée', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together={('commande', 'article', 'variante_id')},
        ),
    ]
