# Generated by Django 5.1.7 on 2025-08-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS'), ('MODIFICATION', 'Modification'), ('PROBLEME_SIGNALÉ', 'Problème signalé'), ('RENVOI_PREPARATION', 'Renvoi en préparation'), ('AFFECTATION_SUPERVISION', 'Affectation par supervision'), ('REAFFECTATION_SUPERVISION', 'Réaffectation par supervision')], max_length=30),
        ),
    ]
