# Generated by Django 5.1.7 on 2025-08-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_modele'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='panier',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='article.variantearticle'),
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together={('commande', 'article', 'variante')},
        ),
    ]
