# Generated by Django 5.1.7 on 2025-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_operation_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS'), ('MODIFICATION', 'Modification'), ('PROBLEME_SIGNALÉ', 'Problème signalé'), ('RENVOI_PREPARATION', 'Renvoi en préparation'), ('AFFECTATION_SUPERVISION', 'Affectation par supervision'), ('REAFFECTATION_SUPERVISION', 'Réaffectation par supervision'), ('AFFECTATION_ADMIN', 'Affectation par admin'), ('REAFFECTATION_ADMIN', 'Réaffectation par admin')], max_length=30),
        ),
    ]
