# Generated by Django 5.1.7 on 2025-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_etatcommande_operateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumetatcmd',
            options={'ordering': ['ordre', 'libelle'], 'verbose_name': "Définition d'état de commande(EnumEtatCmd)", 'verbose_name_plural': "Définitions d'états de commande(EnumEtatCmd)"},
        ),
    ]
