# Generated by Django merge - resolving panier fields conflict

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_add_variante_id_to_panier'),
        ('commande', '0002_alter_panier_unique_together_panier_variante_and_more'),
    ]

    operations = [
        # Cette migration merge les deux branches conflictuelles
        # Les opérations sont déjà appliquées dans les migrations parentes
    ]