# Generated by Django 5.1.7 on 2025-08-25 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_operation_type_operation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='envoi',
            name='commande_en_date_en_d5ea88_idx',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='date_report',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='livreur',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='motif_report',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='notes_livraison',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='notes_preparation',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='operateur_modification',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='poids_total',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='valeur_totale',
        ),
        migrations.AlterField(
            model_name='envoi',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='commande.commande'),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='date_envoi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='date_livraison_effective',
            field=models.DateField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='status',
            field=models.CharField(choices=[('en_preparation', 'En préparation'), ('en_attente', 'En attente de livraison'), ('en_cours', 'En cours de livraison'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20),
        ),
    ]
