# Generated by Django 5.1.7 on 2025-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_commande_ville_init_alter_commande_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_init',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit_init',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
