# Generated by Django 5.1.7 on 2025-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_remove_envoi_commande_en_date_en_d5ea88_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
