# Generated by Django 5.1.7 on 2025-06-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_commande_client_init_commande_produit_init_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='client_init',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='telephone',
        ),
    ]
