# Generated by Django 5.1.7 on 2025-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_alter_envoi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='status',
            field=models.BooleanField(default=True, verbose_name='En cours'),
        ),
    ]
