# Generated by Django 5.1.7 on 2025-06-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_remove_commande_client_init_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='etat_paiement',
        ),
    ]
