# Generated by Django 5.1.7 on 2025-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_populate_etats_commande'),
        ('commande', '0007_remove_commande_etat_paiement'),
    ]

    operations = [
    ]
