# Generated by Django 5.1.7 on 2025-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_merge_20250616_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etatcommande',
            options={'ordering': ['-date_debut'], 'verbose_name': 'État de commande(Suivi de commande)', 'verbose_name_plural': 'États de commande(Suivi de commande)'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_yz',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
