# Generated by Django 5.1.7 on 2025-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_alter_etatcommande_options_alter_commande_id_yz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id_yz',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
