# Generated by Django 5.1.7 on 2025-06-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_alter_commande_id_yz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_cmd', '-date_creation', 'id_yz'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
