# Generated by Django 5.1.7 on 2025-06-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_alter_commande_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('ANNULATION', 'Annulation'), ('PREPARATION', 'Préparation'), ('EXPEDITION', 'Expédition'), ('LIVRAISON', 'Livraison'), ('RETOUR', 'Retour'), ('MODIFICATION', 'Modification'), ('COMMENTAIRE', 'Commentaire'), ('AUCUNE_ACTION', 'Aucune action'), ('APPEL_1', 'Appel 1'), ('APPEL_2', 'Appel 2'), ('APPEL_3', 'Appel 3'), ('APPEL_4', 'Appel 4'), ('APPEL_5', 'Appel 5'), ('APPEL_6', 'Appel 6'), ('APPEL_7', 'Appel 7'), ('APPEL_8', 'Appel 8'), ('ENVOI_SMS', 'Envoi de SMS'), ('ENVOI_MSG', 'Envoi de MSG'), ('PROPOSITION_ABONNEMENT', "Proposition d'un abonnement"), ('PROPOSITION_REDUCTION', "Proposition d'une offre de réduction")], max_length=30),
        ),
    ]
