# Generated by Django 5.1.7 on 2025-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_add_confirmation_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='commentaire',
            field=models.TextField(blank=True, choices=[('Commande Annulée', 'Commande Annulée'), ('Client hésitant', 'Client hésitant'), ('Client intéressé', 'Client intéressé'), ('Client non intéressé', 'Client non intéressé'), ('Client non joignable', 'Client non joignable'), ('commande reportée', 'commande reportée'), ('Article non disponible', 'Article non disponible')], null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS')], max_length=30),
        ),
    ]
