# Generated by Django 5.1.7 on 2025-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0013_operation_commentaire_alter_operation_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='origine',
            field=models.CharField(choices=[('OC', 'Opérateur Confirmation'), ('ADMIN', 'Administrateur'), ('SYNC', 'Synchronisation')], default='SYNC', max_length=10),
        ),
    ]
