# Generated by Django 5.1.7 on 2025-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande", "0014_add_commande_origine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type_operation",
            field=models.CharField(
                choices=[
                    ("APPEL", "Appel "),
                    ("Appel Whatsapp", "Appel Whatsapp"),
                    ("Message Whatsapp", "Appel Whatsapp "),
                    ("Vocal Whatsapp", "Vocal Whatsapp "),
                    ("ENVOI_SMS", "Envoi de SMS"),
                    ("REMPLACEMENT", "Remplacement"),
                    ("MODIFICATION_PREPA", "Modification (Préparation)"),
                ],
                max_length=50,
            ),
        ),
    ]
