# Generated by Django 5.1.7 on 2025-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0015_alter_operation_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='compteur',
            field=models.IntegerField(default=0, verbose_name="Compteur d'utilisation"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS'), ('MODIFICATION', 'Modification')], max_length=30),
        ),
    ]
