# Generated by Django 5.1.7 on 2025-07-04 12:28

from django.db import migrations

def add_sav_states(apps, schema_editor):
    EnumEtatCmd = apps.get_model('commande', 'EnumEtatCmd')
    
    sav_states = [
        {'libelle': 'Reportée', 'ordre': 60, 'couleur': '#F59E0B'},
        {'libelle': 'Livrée Partiellement', 'ordre': 70, 'couleur': '#3B82F6'},
        {'libelle': 'Livrée avec changement', 'ordre': 71, 'couleur': '#8B5CF6'},
        {'libelle': 'Annulée (SAV)', 'ordre': 101, 'couleur': '#EF4444'},
    ]
    
    for state_data in sav_states:
        EnumEtatCmd.objects.get_or_create(
            libelle=state_data['libelle'],
            defaults={'ordre': state_data['ordre'], 'couleur': state_data['couleur']}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0016_commande_compteur_alter_operation_type_operation'),
    ]

    operations = [
        migrations.RunPython(add_sav_states),
    ]
