# Generated by Django 5.1.7 on 2025-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0017_add_sav_delivery_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière synchronisation'),
        ),
    ]
