# Generated by Django 5.1.7 on 2025-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0018_commande_last_sync_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
    ]
