# Generated by Django 5.1.7 on 2025-07-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0019_commande_date_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison',
        ),
    ]
