# Generated by Django 5.1.7 on 2025-07-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0020_remove_commande_date_livraison'),
        ('parametre', '0004_add_historique_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison_prevue', models.DateField(verbose_name='Date de livraison prévue')),
                ('date_report', models.DateField(blank=True, null=True, verbose_name='Date de report')),
                ('motif_report', models.TextField(blank=True, null=True, verbose_name='Motif du report')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de livraison'), ('reporte', 'Reporté'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='commande.commande')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois', to='parametre.operateur')),
            ],
            options={
                'verbose_name': 'Envoi',
                'verbose_name_plural': 'Envois',
                'ordering': ['-date_creation'],
            },
        ),
    ]
