# Generated by Django 5.1.7 on 2025-07-15 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0021_envoi'),
        ('parametre', '0004_add_historique_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoi',
            name='operateur',
        ),
        migrations.AddField(
            model_name='commande',
            name='envoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_associees', to='commande.envoi'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='date_envoi',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date prévue pour l'envoi", verbose_name="Date d'envoi"),
        ),
        migrations.AddField(
            model_name='envoi',
            name='date_livraison_effective',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison effective'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='livreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_livraison': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois_livraison', to='parametre.operateur'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='nb_commandes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='notes_livraison',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de livraison'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='notes_preparation',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de préparation'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='numero_envoi',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'envoi"),
        ),
        migrations.AddField(
            model_name='envoi',
            name='operateur_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois_crees', to='parametre.operateur', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='operateur_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois_modifies', to='parametre.operateur', verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='poids_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids total (kg)'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois', to='parametre.region'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='valeur_totale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur totale (FCFA)'),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires généraux'),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='status',
            field=models.CharField(choices=[('en_preparation', 'En préparation'), ('en_attente', 'En attente de livraison'), ('en_cours', 'En cours de livraison'), ('reporte', 'Reporté'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['date_envoi', 'livreur'], name='commande_en_date_en_d5ea88_idx'),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['status', 'date_creation'], name='commande_en_status_5a803b_idx'),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['region', 'date_envoi'], name='commande_en_region__0615d1_idx'),
        ),
    ]
