# Generated by Django 5.1.7 on 2025-07-15 14:09

from django.db import migrations
from django.utils import timezone


def generer_numeros_envoi(apps, schema_editor):
    """Générer les numéros d'envoi manquants pour les enregistrements existants"""
    Envoi = apps.get_model('commande', 'Envoi')
    
    # Obtenir tous les envois sans numéro
    envois_sans_numero = Envoi.objects.filter(numero_envoi='')
    
    for i, envoi in enumerate(envois_sans_numero, 1):
        # Générer un numéro d'envoi basé sur la date de création
        date_creation = envoi.date_creation or timezone.now()
        numero = f"ENV-{date_creation.strftime('%Y%m%d')}-{i:04d}"
        
        # Vérifier l'unicité et ajuster si nécessaire
        while Envoi.objects.filter(numero_envoi=numero).exists():
            i += 1
            numero = f"ENV-{date_creation.strftime('%Y%m%d')}-{i:04d}"
        
        envoi.numero_envoi = numero
        envoi.save(update_fields=['numero_envoi'])


def reverse_generer_numeros_envoi(apps, schema_editor):
    """Fonction inverse (optionnelle)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0022_remove_envoi_operateur_commande_envoi_and_more'),
    ]

    operations = [
        migrations.RunPython(
            generer_numeros_envoi, 
            reverse_generer_numeros_envoi
        ),
    ]
