# Generated by Django 5.1.7 on 2025-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0023_auto_20250715_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS'), ('MODIFICATION', 'Modification'), ('PROBLEME_SIGNALÉ', 'Problème signalé'), ('RENVOI_PREPARATION', 'Renvoi en préparation')], max_length=30),
        ),
    ]
