# Generated by Django 5.1.7 on 2025-07-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_remove_article_prix_unitaire_positif_and_more'),
        ('commande', '0024_alter_operation_type_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatArticleRenvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_articles_renvoyes', to='commande.commande')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commande.enumetatcmd')),
            ],
            options={
                'verbose_name': "État d'article renvoyé",
                'verbose_name_plural': "États d'articles renvoyés",
                'unique_together': {('commande', 'article')},
            },
        ),
    ]
