# Generated by Django 5.1.7 on 2025-08-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0025_etatarticlerenvoye'),
        ('parametre', '0005_alter_operateur_type_operateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='livreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_operateur': 'LOGISTIQUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envois_livraison', to='parametre.operateur'),
        ),
    ]
