# Generated by Django 5.1.7 on 2025-06-13 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('couleur', models.CharField(max_length=50)),
                ('pointure', models.CharField(max_length=10)),
                ('prix_unitaire', models.FloatField()),
                ('categorie', models.CharField(max_length=100)),
                ('qte_disponible', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom', 'couleur', 'pointure'],
                'constraints': [models.CheckConstraint(condition=models.Q(('prix_unitaire__gt', 0)), name='prix_unitaire_positif'), models.CheckConstraint(condition=models.Q(('qte_disponible__gte', 0)), name='qte_disponible_positif')],
                'unique_together': {('nom', 'couleur', 'pointure')},
            },
        ),
    ]
