# Generated by Django 5.1.7 on 2025-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
