# Generated by Django 5.1.7 on 2025-08-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_genre_mouvementstock_commande_associee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantearticle',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='variantearticle',
            name='prix_actuel',
        ),
        migrations.RemoveField(
            model_name='variantearticle',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='variantearticle',
            name='reference_variante',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
