# Generated by Django 5.1.7 on 2025-06-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
