# Generated by Django 5.1.7 on 2025-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_categorie_nom_alter_genre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('SANDALES', 'Sandales'), ('SABOT', 'Sabot'), ('CHAUSSURES', 'Chaussures'), ('ESPARILLE', 'Espadrilles'), ('BASKET', 'Baskets'), ('MULES', 'Mules'), ('PACK_SAC', 'Pack Sac'), ('BOTTE', 'Bottes'), ('ESCARPINS', 'Escarpins')], default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='nom',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('FILLE', 'Fille'), ('GARCON', 'Garçon')], default='', max_length=20, unique=True),
        ),
    ]
