# Generated by Django 5.1.7 on 2025-06-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_prix_unitaire'),
    ]

    operations = [
        # Migration vide - la contrainte pointure_valide a été supprimée car elle pose problème avec SQLite
    ]
