# Generated by Django 5.1.7 on 2025-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_prix_unitaire'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('pointure__regex', '^(3[0-9]|4[0-9]|50)$')), name='pointure_valide'),
        ),
    ]
