# Generated by Django 5.1.7 on 2025-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_variantearticle_prix_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modele',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
