# Generated by Django optimization for YZ-CMD

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_modele'),
        ('commande', '0002_alter_panier_unique_together_panier_variante_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_article_actif_phase ON article_article(actif, phase);",
            reverse_sql="DROP INDEX IF EXISTS idx_article_actif_phase;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_article_actif_isupsell ON article_article(actif, \"isUpsell\");",
            reverse_sql="DROP INDEX IF EXISTS idx_article_actif_isupsell;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_article_search_fields ON article_article(nom, reference, actif);",
            reverse_sql="DROP INDEX IF EXISTS idx_article_search_fields;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_variante_actif_qte ON article_variantearticle(actif, qte_disponible);",
            reverse_sql="DROP INDEX IF EXISTS idx_variante_actif_qte;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_variante_article_actif ON article_variantearticle(article_id, actif);",
            reverse_sql="DROP INDEX IF EXISTS idx_variante_article_actif;"
        ),
    ]