# Generated by Django 5.1.7 on 2025-07-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upsell_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_1_articles', to='article.article', verbose_name='Produit complémentaire 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='upsell_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_2_articles', to='article.article', verbose_name='Produit complémentaire 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='upsell_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_3_articles', to='article.article', verbose_name='Produit complémentaire 3'),
        ),
    ]
