# Generated by Django 5.1.7 on 2025-07-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_upsell_1_article_upsell_2_article_upsell_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='upsell_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upsell_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upsell_3',
        ),
        migrations.AddField(
            model_name='article',
            name='prix_upsell_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_upsell_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_upsell_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 3'),
        ),
    ]
