# Generated by Django 5.1.7 on 2025-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_upsell_1_remove_article_upsell_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='code_promo',
        ),
        migrations.AddField(
            model_name='article',
            name='isUpsell',
            field=models.BooleanField(default=False, verbose_name='Est un upsell'),
        ),
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('EN_COURS', 'En Cours'), ('LIQUIDATION', 'Liquidation'), ('EN_TEST', 'En Test')], default='EN_COURS', max_length=20, verbose_name="Phase de l'article"),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='articles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'phase': 'EN_COURS'}, related_name='promotions', to='article.article'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('isUpsell', False), ('phase', 'EN_COURS'), _connector='OR'), name='upsell_seulement_en_cours'),
        ),
    ]
