# Generated by Django 5.1.7 on 2025-07-04 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_remove_promotion_code_promo_article_isupsell_and_more'),
        ('commande', '0017_add_sav_delivery_states'),
        ('parametre', '0004_add_historique_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isUpsell', models.BooleanField(default=False)),
                ('qte_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement_pos', 'Ajustement Positif'), ('ajustement_neg', 'Ajustement Négatif'), ('inventaire', 'Inventaire'), ('retour_client', 'Retour Client')], max_length=20)),
                ('quantite', models.IntegerField(help_text='Quantité du mouvement. Positive pour une entrée, négative pour une sortie.')),
                ('qte_apres_mouvement', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='article.article')),
                ('commande_associee', models.ForeignKey(blank=True, help_text='Commande liée à ce mouvement (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.commande')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametre.operateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
