# Generated by Django 5.1.7 on 2025-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_categorie_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_barre',
            field=models.CharField(blank=True, help_text='Code-barres EAN13, UPC ou autre format', max_length=100, null=True, unique=True, verbose_name='Code-barres'),
        ),
    ]
