# Generated by Django 5.1.7 on 2025-07-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_add_code_barre_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code_barre',
        ),
    ]
