# Generated by Django 5.1.7 on 2025-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_remove_article_code_barre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.RemoveConstraint(
            model_name='article',
            name='upsell_seulement_en_cours',
        ),
    ]
