# Generated by Django 5.1.7 on 2025-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_upsell_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 4'),
        ),
    ]
