# Generated by Django 5.1.7 on 2025-07-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '000X_alter_prix_unitaire_positif'),
        ('article', '0014_article_image_url'),
    ]

    operations = [
    ]
