# Generated by Django 5.1.7 on 2025-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_merge_20250722_1258'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='prix_unitaire_positif',
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gt', 0)), name='prix_unitaire_positif'),
        ),
    ]
