# Generated by Django 5.1.7 on 2025-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_remove_article_prix_unitaire_positif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('EN_COURS', 'En Cours'), ('LIQUIDATION', 'Liquidation'), ('EN_TEST', 'En Test'), ('PROMO', 'Promo')], default='EN_COURS', max_length=20, verbose_name="Phase de l'article"),
        ),
    ]
