# Generated by Django 5.1.7 on 2025-08-18 16:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_add_promo_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('code_hex', models.CharField(blank=True, help_text='Code couleur hexadécimal (ex: #FF0000)', max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('FILLE', 'Fille'), ('GARCON', 'Garçon')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pointure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointure', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage des pointures")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pointure',
                'verbose_name_plural': 'Pointures',
                'ordering': ['ordre', 'pointure'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('SANDALES', 'Sandales'), ('SABOT', 'Sabot'), ('CHAUSSURES', 'Chaussures'), ('ESPARILLE', 'Espadrilles'), ('BASKET', 'Baskets'), ('MULES', 'Mules'), ('PACK_SAC', 'Pack Sac'), ('BOTTE', 'Bottes'), ('ESCARPINS', 'Escarpins')], default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='isUpsell',
            field=models.BooleanField(default=False, verbose_name='Est un upsell'),
        ),
        migrations.CreateModel(
            name='VarianteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_actuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='article.article')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.couleur')),
                ('pointure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.pointure')),
            ],
            options={
                'verbose_name': "Variante d'article",
                'verbose_name_plural': "Variantes d'articles",
                'ordering': ['article__nom', 'couleur__nom', 'pointure__pointure'],
                'unique_together': {('article', 'couleur', 'pointure')},
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='article.variantearticle'),
        ),
    ]
