# Generated by Django 5.1.7 on 2025-08-22 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parametre', models.CharField(help_text='Nom unique du paramètre', max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('seuils', "Seuils d'alerte"), ('calcul', 'Paramètres de calcul'), ('affichage', "Préférences d'affichage")], default='seuils', max_length=20)),
                ('valeur', models.FloatField(help_text='Valeur numérique du paramètre')),
                ('description', models.TextField(help_text='Description et utilité du paramètre')),
                ('unite', models.CharField(blank=True, help_text='Unité de mesure (%, jours, etc.)', max_length=20)),
                ('valeur_min', models.FloatField(blank=True, help_text='Valeur minimum autorisée', null=True)),
                ('valeur_max', models.FloatField(blank=True, help_text='Valeur maximum autorisée', null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration KPI',
                'verbose_name_plural': 'Configurations KPIs',
                'ordering': ['categorie', 'nom_parametre'],
            },
        ),
    ]
