# Generated by Django 5.1.7 on 2025-06-24 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('seuil', "Seuils d'alerte"), ('periode', "Périodes d'analyse"), ('formule', 'Formules de calcul'), ('objectif', 'Objectifs métier')], max_length=20)),
                ('nom_parametre', models.CharField(max_length=100, unique=True)),
                ('nom_affiche', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('valeur_defaut', models.FloatField()),
                ('valeur_actuelle', models.FloatField()),
                ('type_valeur', models.CharField(choices=[('int', 'Nombre entier'), ('float', 'Nombre décimal'), ('percent', 'Pourcentage'), ('days', 'Jours')], max_length=10)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('valeur_min', models.FloatField()),
                ('valeur_max', models.FloatField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration KPI',
                'verbose_name_plural': 'Configurations KPI',
                'ordering': ['categorie', 'nom_parametre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.FloatField()),
                ('nouvelle_valeur', models.FloatField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='kpis.kpiconfiguration')),
            ],
            options={
                'verbose_name': 'Historique Configuration',
                'verbose_name_plural': 'Historiques Configuration',
                'ordering': ['-date_modification'],
            },
        ),
    ]
