# Generated by Django 5.1.7 on 2025-06-25 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiconfiguration',
            options={'ordering': ['categorie', 'nom_parametre'], 'verbose_name': 'Configuration KPI', 'verbose_name_plural': 'Configurations KPIs'},
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='nom_affiche',
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='type_valeur',
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='valeur_actuelle',
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='valeur_defaut',
        ),
        migrations.AddField(
            model_name='kpiconfiguration',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpiconfiguration',
            name='valeur',
            field=models.FloatField(default=0.0, help_text='Valeur numérique du paramètre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='categorie',
            field=models.CharField(choices=[('seuils', "Seuils d'alerte"), ('calcul', 'Paramètres de calcul'), ('affichage', "Préférences d'affichage")], default='seuils', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='description',
            field=models.TextField(help_text='Description et utilité du paramètre'),
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='nom_parametre',
            field=models.CharField(help_text='Nom unique du paramètre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='unite',
            field=models.CharField(blank=True, help_text='Unité de mesure (%, jours, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='valeur_max',
            field=models.FloatField(blank=True, help_text='Valeur maximum autorisée', null=True),
        ),
        migrations.AlterField(
            model_name='kpiconfiguration',
            name='valeur_min',
            field=models.FloatField(blank=True, help_text='Valeur minimum autorisée', null=True),
        ),
        migrations.DeleteModel(
            name='HistoriqueConfiguration',
        ),
    ]
