# Generated by Django 5.1.7 on 2025-08-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_url', models.URLField(verbose_name='URL de la feuille Google Sheet')),
                ('sheet_name', models.CharField(max_length=100, verbose_name='Nom de la feuille')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed_row', models.IntegerField(default=0, help_text='Numéro de la dernière ligne traitée lors de la synchronisation précédente', verbose_name='Dernière ligne traitée')),
            ],
            options={
                'verbose_name': 'Configuration Google Sheet',
                'verbose_name_plural': 'Configurations Google Sheet',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de synchronisation')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('partial', 'Partiel')], max_length=10, verbose_name='Statut')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Enregistrements importés')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Erreurs')),
                ('triggered_by', models.CharField(max_length=100, verbose_name='Déclenché par')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('total_rows', models.IntegerField(blank=True, null=True, verbose_name='Total lignes dans la feuille')),
                ('processed_rows', models.IntegerField(blank=True, null=True, verbose_name='Lignes traitées')),
                ('skipped_rows', models.IntegerField(blank=True, null=True, verbose_name='Lignes ignorées')),
                ('sheet_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre de la feuille')),
                ('execution_details', models.JSONField(blank=True, null=True, verbose_name="Détails d'exécution")),
                ('new_orders_created', models.IntegerField(default=0, verbose_name='Nouvelles commandes créées')),
                ('existing_orders_updated', models.IntegerField(default=0, verbose_name='Commandes existantes mises à jour')),
                ('existing_orders_skipped', models.IntegerField(default=0, verbose_name='Commandes existantes inchangées')),
                ('duplicate_orders_found', models.IntegerField(default=0, verbose_name='Doublons détectés et évités')),
                ('protected_orders_count', models.IntegerField(default=0, verbose_name="Commandes protégées contre la régression d'état")),
                ('sheet_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='synchronisation.googlesheetconfig')),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-sync_date'],
            },
        ),
    ]
