# Generated by Django 5.1.7 on 2025-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='execution_details',
            field=models.JSONField(blank=True, null=True, verbose_name="Détails d'exécution"),
        ),
        migrations.AddField(
            model_name='synclog',
            name='processed_rows',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lignes traitées'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sheet_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre de la feuille'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='skipped_rows',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lignes ignorées'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_rows',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total lignes dans la feuille'),
        ),
    ]
